[project]
name = "health_data_parser"
version = "0.1.0"
description = "health_data_parser"
requires-python = ">=3.12,<3.14"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "tabulate>=0.9.0",
]
